version: '3'
services:
  root:
    build:
      context: ./root
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  home:
    build:
      context: ./home
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
