version: '3'
services:
  root:
    build:
      context: ./root
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  home:
    build:
      context: ./home
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./ssl:/app/ssl # Menambahkan volume untuk sertifikat SSL

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx.crt:/etc/nginx/nginx.crt
      - ./nginx/nginx.key:/etc/nginx/nginx.key
      - ./ssl:/etc/nginx/ssl # Menambahkan volume untuk sertifikat SSL
